#!/bin/bas

# Place the current date in the formate of YYYY-MM-DD into a variable called DATE_NOW via the data command to be printed in the report
DATE_NOW=$(date +"%Y-%m-%d")

# This gets the distrobution name and places it into a variable called DISTRO_NAME to be printed in the report
DISTRO_NAME=$(source /etc/os-release; echo $NAME)

# This gets the distrobution version and places it into a variable called DISTRO_VERSION to be printed in the report
DISTRO_VERSION=$(source /etc/os-release; echo $VERSION)

# This gets the uptime and places it into a variable called UPTIME to be printed in the report
UPTIME=$(uptime)

#This gets the CPU make and model and puts it into a variable called CPU_INFO to be printed in the report
# it does this by first listing the CPU section of lshw, then it uses grep to find only the product lines (of which there are multiple),
# then it uses awk to grab only the first line of the multiple product lines from grep (all of which are duplicates),
# in that same awk replaces the first word (which is the "product:" that grep found) with a blank (""),
# and lastly does a print so that the output can be placed into the CPU_INFO variable
CPU_INFO=$(lshw -C cpu | grep product | awk 'NR==1 { $1=""; print }')

# THIS gets the RAM size and places it into a variable called RAM_SIZE to be printed in the report later
# the process of getting the ram size is nearly identical to the CPU info exept we look for the memory section of lshw and we grep for size
RAM_SIZE=$(lshw -C memory | grep size | awk 'NR==1 { $1=""; print }')

# this prints a system report using the variables made earlier to print data dynamically
cat << EOF
System Report for $HOSTNAME generated by $USER, on $DATE_NOW

System Information
------------------
OS: $DISTRO_NAME $DISTRO_VERSION
Uptime: $UPTIME
CPU: $CPU_INFO
RAM: $RAM_SIZE
Disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS
Video: MAKE AND MODEL OF VIDEO CARD
Host Address: IP ADDRESS FOR THE INTERFACE THAT IS CONNECTED TO THE DEFAULT GATEWAY
Gateway IP: DEFAULT GATEWAY ADDRESS
DNS Server: IP OF DNS SERVER

System Status
-------------
Users Logged In: USER,USER,USER...
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: N
Load Averages: N, N, N
Listening Network Ports: N, N, N, ...
UFW Status: UFWSTATUS

EOF
